name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    volumes:
      - dataset:/var/lib/client/data
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=MAFER
      - APELLIDO=PONT
      - DOCUMENTO=111111
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    volumes:
      - dataset:/var/lib/client/data
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=MAFER
      - APELLIDO=PONT
      - DOCUMENTO=222222
      - NACIMIENTO=1999-03-17
      - NUMERO=7575
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    volumes:
      - dataset:/var/lib/client/data
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=MAFER
      - APELLIDO=PONT
      - DOCUMENTO=333333
      - NACIMIENTO=1999-03-17
      - NUMERO=7576
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    volumes:
      - dataset:/var/lib/client/data
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=MAFER
      - APELLIDO=PONT
      - DOCUMENTO=444444
      - NACIMIENTO=1999-03-17
      - NUMERO=7577
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    volumes:
      - dataset:/var/lib/client/data
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=MAFER
      - APELLIDO=PONT
      - DOCUMENTO=555555
      - NACIMIENTO=1999-03-17
      - NUMERO=7578
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: ${PWD}/.data